apiVersion: v1
kind: Template
metadata:
  name: coolstore-ansible-installer
parameters:
- displayName: Playbooks Git Repo
  value: "https://github.com/siamaksade/openshift-demos-ansible"
  name: GITHUB_REPO
  required: true
- displayName: Playbooks Git Ref
  value: master
  name: GITHUB_REF
  required: true
- displayName: CoolStore Demo Name
  description: The name of the coolstore demo to deploy e.g. msa-cicd-eap-full, msa-cicd-eap-min, msa-full, msa-min
  value: msa-min
  name: DEMO_NAME
  required: true
- displayName: CoolStore GitHub Account
  value: jbossdemocentral
  name: COOLSTORE_GITHUB_ACCOUNT
  required: true
- displayName: CoolStore GitHub Ref
  value: stable-ocp-3.10
  name: COOLSTORE_GITHUB_REF
  required: true
- displayName: Maven Mirror URL
  name: MAVEN_MIRROR_URL
- displayName: Project Suffix
  description: Suffix to add to project names e.g. cicd-[SUFFIX]
  name: PROJECT_SUFFIX
  value: demo
  required: true
- displayName: Project Admin
  description: Use to be assigned as the project admin for demo projects
  name: PROJECT_ADMIN
  required: true
- displayName: Ephemeral
  description: Deploy without persistent storage
  name: EPHEMERAL
  value: "false"
  required: true
- displayName: Deploy Guides
  name: DEPLOY_GUIDES
  value: "true"
  required: true
- displayName: Ansible Extra Vars
  description: A space separated list of key=value pairs to pass to the Ansible playbook as extra vars
  name: ANSIBLE_EXTRA_VARS
  required: false
- displayName: Ansible Playbooks Version
  name: ANSIBLE_PLAYBOOKS_VERSION
  required: true
  value: master
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: coolstore-ansible-installer
  spec:
    activeDeadlineSeconds: 1800
    completions: 1
    parallelism: 1
    backoffLimit: 10
    template:
      spec:
        containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
          - /demos/playbooks/coolstore/${DEMO_NAME}.yml 
          - -e
          - "github_account=${COOLSTORE_GITHUB_ACCOUNT} github_ref=${COOLSTORE_GITHUB_REF} project_admin=${PROJECT_ADMIN} project_suffix=${PROJECT_SUFFIX} ephemeral=${EPHEMERAL} deploy_guides=${DEPLOY_GUIDES} ${ANSIBLE_EXTRA_VARS}"
          image: siamaksade/openshift-demos-ansible:${ANSIBLE_PLAYBOOKS_VERSION}
          name: coolstore-ansible-installer-job
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        restartPolicy: Never