---
- name: Idle Coolstore Microservices Demo
  hosts: localhost
  gather_facts: false
  run_once: true
  tasks:
    - include_role:
        name: openshift_common_facts

    - name: idling projects
      shell: "{{ openshift_cli }} idle -n {{ item }} --all"
      ignore_errors: true
      with_items:
        - "{{ project_default }}"
        - "{{ project_cicd }}"
        - "{{ project_prod }}"
        - "{{ project_stage }}"
        - "{{ project_test }}"
        - "{{ project_dev }}"