---
- name: Deploy Coolstore Microservices Demo
  hosts: localhost
  gather_facts: false
  run_once: true
  vars_files:
    - demo_vars/msa/all

  tasks:
    - include_role:
        name: openshift_common_facts

    - import_role:
        name: openshift_coolstore
      vars:
        project_annotations: "demo=demo-msa-{{ project_suffix }}"
        hostname_suffix: "{{ apps_hostname_suffix }}"
        enable_cicd: false
        src_github_account: "{{ github_account }}"
        src_github_ref: stable-{{ github_ref }}

    # verify deployed successfully
    - include_tasks: verify_all.yml
      tags: verify